[package]
edition = "2021"
name = "bf"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
# 仮
path = "src/main.rs"
name = "bf_t"

[dependencies]
serde = {version = "1.0.134", features = ["derive"]}
serde_json = "1.0.76"
thiserror = "1.0.30"

[dev-dependencies]
rstest = "0.12.0"
