[package]
edition = "2021"
name = "bf"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.5"
log = "0.4.16"
serde = {version = "1.0.134", features = ["derive"]}
serde_json = "1.0.76"
thiserror = "1.0.30"

[dev-dependencies]
rstest = "0.15.0"
